# Generated by Django 5.1.3 on 2024-12-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_studio_user_favoritestudio"),
    ]

    operations = [
        migrations.AddField(
            model_name="studio",
            name="self_practice_reservation_start_date",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
