# Generated by Django 5.1.3 on 2024-02-19 21:33

from django.db import migrations, models
from datetime import timedelta

def convert_to_duration(apps, schema_editor):
    Studio = apps.get_model('api', 'Studio')
    for studio in Studio.objects.all():
        if studio.self_practice_reservation_start_date is not None:
            studio.self_practice_reservation_start_date = timedelta(days=studio.self_practice_reservation_start_date)
            studio.save()

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_studio_self_practice_reservation_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='self_practice_reservation_start_date_duration',
            field=models.DurationField(blank=True, help_text='個人練習の予約開始可能までの日にち', null=True),
        ),
        migrations.RunPython(convert_to_duration),
        migrations.RemoveField(
            model_name='studio',
            name='self_practice_reservation_start_date',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='self_practice_reservation_start_date_duration',
            new_name='self_practice_reservation_start_date',
        ),
        migrations.AddField(
            model_name='studio',
            name='closes_next_day',
            field=models.BooleanField(default=False, help_text='閉店時間が翌日の場合はTrue'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='closing_time',
            field=models.TimeField(help_text='閉店時間'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='opening_time',
            field=models.TimeField(help_text='開店時間'),
        ),
    ]
