# Generated by Django 5.1.3 on 2024-12-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_studio_self_practice_reservation_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="studio",
            name="closes_next_day",
            field=models.BooleanField(default=False, help_text="閉店時間が翌日の場合はTrue"),
        ),
        migrations.AlterField(
            model_name="studio",
            name="closing_time",
            field=models.TimeField(help_text="閉店時間"),
        ),
        migrations.AlterField(
            model_name="studio",
            name="opening_time",
            field=models.TimeField(help_text="開店時間"),
        ),
        migrations.AlterField(
            model_name="studio",
            name="self_practice_reservation_start_date",
            field=models.DurationField(
                blank=True, help_text="個人練習の予約開始可能までの日にち", null=True
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="self_practice_reservation_start_time",
            field=models.DurationField(
                blank=True, help_text="個人練習の予約開始可能時間", null=True
            ),
        ),
    ]
