# Generated by Django 5.1.3 on 2024-12-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_studio_closes_next_day_alter_studio_closing_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studio",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="studio",
            name="self_practice_reservation_start_date",
        ),
        migrations.RemoveField(
            model_name="studio",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="studio",
            name="self_practice_reservation_start_days_before",
            field=models.PositiveIntegerField(
                blank=True, help_text="個人練習の予約開始可能までの日数（例：7日前）", null=True
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="self_practice_reservation_start_time",
            field=models.TimeField(blank=True, help_text="個人練習の予約開始時間", null=True),
        ),
    ]
