# Generated by Django 5.1.3 on 2024-12-22 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_studio_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studio",
            old_name="self_practice_reservation_start_days_before",
            new_name="self_practice_reservation_start_day",
        ),
    ]
