# Generated by Django 5.1.3 on 2024-12-22 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0006_rename_self_practice_reservation_start_days_before_studio_self_practice_reservation_start_day",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studio",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studio",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
