# Generated by Django 5.1.3 on 2024-12-22 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_studio_created_at_studio_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studio",
            old_name="self_practice_reservation_start_day",
            new_name="self_practice_reservation_start_date",
        ),
    ]
