# Generated by Django 5.1.3 on 2025-01-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_self_practice_reservation_start_day_studio_self_practice_reservation_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='is_24h',
            field=models.BooleanField(default=False, help_text='24時間営業の場合はTrue'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='閉店時間（24時間営業の場合は空）', null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='開店時間（24時間営業の場合は空）', null=True),
        ),
    ]
